import { useEffect, useState, useContext } from "react";
import { getUserBookings, cancelBooking } from "../services/bookingService";
import { AuthContext } from "../context/AuthContext";
import toast from "react-hot-toast";
import { jsPDF } from "jspdf";

export default function Bookings() {

  const { user } = useContext(AuthContext);
  const [bookings, setBookings] = useState([]);

  useEffect(() => {

    if (!user?.id) return;

    getUserBookings(user.id)
      .then(res => setBookings(res.data))
      .catch(err => console.log(err));

  }, [user]);



  const handleCancel = async (id) => {

    try {

      await cancelBooking(id);

      toast.success("Booking Cancelled");

      setBookings(prev => prev.filter(b => b.id !== id));

    } catch {

      toast.error("Cancellation Failed");

    }

  };



  const downloadTicket = (booking) => {

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("🛕 DarshanEase", 75, 20);

    doc.setLineWidth(0.5);
    doc.line(20, 30, 190, 30);

    doc.setFontSize(16);
    doc.text("Temple Darshan Ticket", 65, 45);

    doc.setFontSize(12);

    doc.text(`Devotee Name: ${user?.name || "Guest"}`, 20, 70);
    doc.text(`Booking ID: ${booking.id}`, 20, 80);
    doc.text(`Darshan Date: ${booking.bookingDate}`, 20, 90);
    doc.text(`Amount Paid: ₹ ${booking.totalAmount}`, 20, 100);

    doc.text("Temple Darshan Pass", 20, 120);
    doc.text("Please arrive 15 minutes before slot time.", 20, 130);

    doc.setFontSize(10);
    doc.text("Generated by DarshanEase Booking System", 60, 180);

    doc.save(`darshan_ticket_${booking.id}.pdf`);
  };



  const handlePayment = (booking) => {

    toast.loading("Processing Payment...");

    setTimeout(() => {

      toast.dismiss();

      toast.success("Payment Successful 🙏");

      downloadTicket(booking);

    }, 2000);

  };



  return (

  <div style={{ padding: "30px" }}>

    <h2>My Bookings</h2>

    {/* Demo ticket button for college presentation */}
    <button
      onClick={() =>
        downloadTicket({
          id: "DEMO123",
          bookingDate: "10 March 2026",
          totalAmount: 200
        })
      }
      style={{
        marginTop: "15px",
        marginBottom: "20px",
        background: "#ff6a00",
        color: "white",
        padding: "8px 14px",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer"
      }}
    >
      Download Demo Ticket
    </button>

    {bookings.length === 0 && <p>No bookings found</p>}

    {bookings.map((b) => (

      <div
        key={b.id}
        style={{
          border: "1px solid #ddd",
          padding: "15px",
          marginBottom: "15px",
          borderRadius: "10px"
        }}
      >

        <p><b>Date:</b> {b.bookingDate}</p>
        <p><b>Amount:</b> ₹ {b.totalAmount}</p>

        <button
          onClick={() => handlePayment(b)}
          style={{
            marginRight: "10px",
            background: "#ff6a00",
            color: "white",
            padding: "6px 12px",
            border: "none",
            borderRadius: "4px"
          }}
        >
          Pay Now
        </button>

        <button
          onClick={() => downloadTicket(b)}
          style={{ marginRight: "10px" }}
        >
          Download Ticket
        </button>

        <button onClick={() => handleCancel(b.id)}>
          Cancel
        </button>

      </div>

    ))}

  </div>

);
}